version: '3'

services:
   db:
     image: mysql:5.6
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: lovd
       MYSQL_USER: lovd
       MYSQL_PASSWORD: lovd

   lovd:
     depends_on:
       - db
     image: welliton/lovd:latest
     ports:
       - "80:80"
     restart: always
     environment:
       LOVD_DB_DRIVER: mysql
       LOVD_DB_HOST: db
       LOVD_DB_NAME: lovd
       LOVD_DB_USER: lovd
       LOVD_DB_PASSWORD: lovd
       LOVD_TABLE_PREFIX: lovd

volumes:
    db_data: